### ISSUE TITLE
Os Princípios Gerais do Projeto que serão utilizados no projeto

### ISSUE THREAD

**Issue by milenaaires** [Interacao-Humano-Computador/2022.2-Aprender3#16]
Descrição: detalhar, justificar e criar documento sobre os princípios gerais que utilizaremos no projeto.

Critério de aceitação: ter tudo documentado no git pages.

- [x] correspondência com as expectativas dos usuários;
- [x] simplicidade nas estruturas das tarefas;
- [x] equilíbrio entre controle e liberdade do usuário;
- [x] consistência e padronização; promoção da eficiência do usuário;
- [x] antecipação das necessidades do usuário;
- [x] visibilidade e reconhecimento;
- [x] conteúdo relevante e expressão adequada; e
- [x] projeto para erros.

**Comment by roddas** [comment]
Dei uma breve descrição de cada tópico.
