### ISSUE TITLE
Finalizar documento de planejamento do PAF

### ISSUE THREAD

**Issue by raphaiela** [Interacao-Humano-Computador/2022.2-Aprender3#48]
## Descrição: 

Finalizar o documento do planejamento dos resultados do protótipo de baixa fidelidade: https://interacao-humano-computador.github.io/2022.2-Aprender3/DesignAvalDesenv/nivel3/prototipo_alta_fidelidade/

## Critérios de aceitação: 

Todas as tarefas da checklist concluídas e postadas no GitHub.

## Tarefas:

- [x] Colocar fonte nas tabelas
- [x] Colocar legendas nas tabelas
- [x] Chamar tabelas no texto

**Comment by roddas** [comment]
Feito
